export default {
  booking_date: "Fecha de Reserva",
  trip_start_time: "Hora de inicio del viaje",
  trip_end_time: "Hora de finalización del viaje",
  customer_name: "Nombre del Cliente",
  car_type: "Tipo de Vehiculo",
  vehicle_no: "Numero de Placa",
  pickup_address: "Dirección de Recoguida",
  pais: "Pais",
  ciudad: "Ciudad",
  drop_address: "Dirección de Llegada",
  assign_driver: "Conductor Asignado",
  booking_status: "Estado de la Reservación",
  trip_cost: "Costo del Viaje",
  discount_ammount: "Descuento",
  payment_status: "Estado de Pago",

  payment_mode: "Modo de Pago",
  booking_text: "Reservas",
  image: "Imagen",
  name: "Nombre",
  rate_per_km: "Tarifa por Kilometro",
  rate_per_hour: "Tarifa por Hora",
  min_fare: "Tarifa Minima",
  convenience_fee: "Tarifas de Conveniencia",
  convenience_fee_percent: "Tarifas de Conveniencia (%)",
  today_text: "Hoy",
  gross_earning: "Total de Ganancias",
  admin_convenience_fee: "Nuestra Ganancia",
  this_month_text: "Mes",
  total: "Total",
  real_time_driver_section_text: "Conductores en Tiempo Real",
  allow_location: "Permitir ubicación para el mapa en tiempo real",
  sign_in: "Inicia Sesión",
  email_address: "Correo Electronico",
  password: "Contraseña",
  sign_in_error:
    "Error de inicio de sesión. Por favor, compruebe el correo electrónico y la contraseña.",
  device_type: "Tipo de Dispositivo",
  user_type: "Tipo de Usuario",
  title: "Titulo",
  body: "Cuerpo",
  push_notification_title: "Enviar Notificación",
  promo_name: "Promoción",
  description: "Descripción",
  promo_type: "Tipo de Promoción",
  promo_discount_value: "Valor de descuento promocional",
  max_limit: "Limite Maximo",
  min_limit: "Limite Minimo",
  start_date: "Fecha de Inicio (Dia/Mes/Año)",
  end_date: "Fecha de Fin (Dia/Mes/Año)",
  promo_usage: "Límite de uso de la promoción",
  promo_used_by: "Promoción usada por",
  promo_offer: "Promociones y Ofertas",
  refferal_bonus: "Bono de Referencia",
  submit: "Enviar",
  update_failed: "Error en la actualización",
  first_name: "Nombre",
  last_name: "Apellido",
  email: "Correo Electronico",
  mobile: "Telefono",
  profile_image: "Imagen de Perfil",
  vehicle_model: "Modelo de Vehiculo",
  account_approve: "Cuenta Aprobada",
  driver_active: "Estado del Conductor",
  lisence_image: "Licencia de Conducir",
  vehicle_number: "Número de Matricula",
  wallet_balance: "Saldo de Billetera",
  signup_via_refferal: "Inscripción a través de la referencia",
  refferal_id: "ID",
  all_user: "Todos los Usuarios",
  notification_sent: "Notificaciones Enviadas.",
  notification_sent_failed: "Error en el envío de notificaciones.",
  no_user_match: "No hay usuarios emparejados",
  no_user_matching:
    "No se han encontrado usuarios que coincidan con su selección.",
  dashboard_text: "Inicio",
  user: "Usuarios",
  booking_history: "Historial de Reservas",
  promo: "Promoción",
  logout: "Cerrar Sesión",
  driver_earning: "Ganancias del Conductor",
  earning_amount: "Importe de la ganancia",
  driver_name: "Nombre del Controlador",
  driver_image: "Imagen del Conductor",
  months: "Meses",
  year: "Años",
  vehicle_type: "Número de Matricula",
  lisence_no: "Licencia de Conducir",
  booking_discount_earning: "Descuento de Reserva",
  trip_cost_driver_share: "Costo del viaje/Cuota del conductor",
  Gross_trip_cost: "Costo del Viaje",
  Discounts: "Descuentos",
  Customer_paid: "Cliente Pagado",
  Profit: "Beneficio ( Cuenta Pagada - Costo del viaje )",
  earning_reports: "Informes de Ganancias",
  cash_payment_amount: "Pago en Efectivo",
  card_payment_amount: "Pago con Tarjeta",
  wallet_payment_amount: "Pago con Billetera",
  payment_getway: "Pago con Getway",
  direction_url: "Coordenadas de Usuario",
  name_client: "Nombre Cliente",
  name_driver: "Nombre Conductor",
  img_drive_perfile: "Foto del conductor",
  hora_emit: "Alerta emitida (Hora)",
};
